Update updates.txt (v.0.2.5+)
shoc71/dont-stop-now pull request #112
Opened 2023-06-30 02:57 UTC by shoc71

2023-06-30 13:29 UTC, slysnivy requested changes
The functions part in the text for v.0.2.1 to v.0.2.5 need more detail. Especially victory counter and time passed because I remember these were in the main game for a long time in the code, but not visually shown in the game.

2023-06-30 13:30 UTC, slysnivy commented
I think some newer additions were built off of these components

2023-07-03 17:20 UTC, slysnivy commented on dont stop now/patch notes/updates.txt
> +- tons of formatting changes being made (difference in which IDE python is being used; VSC and PyCharm)
This comment on formatting is unnecessary, it's mostly there to let you know that there's a difference in formatting/spaces between the classes

2023-07-03 17:21 UTC, slysnivy commented on dont stop now/patch notes/updates.txt
>  - time passed function added
There is no information on a time passed function. Though I believe this is from the comments I made about using pygame.time with various features in dsn_editor or dsn_levels.

2023-07-03 17:24 UTC, slysnivy commented on dont stop now/patch notes/updates.txt
>  - victory counter added
This victory counter comment is also unnecessary. It might be from the comments I made about using victory counter and pygame.time (time passed) to update the memory upon level completion. Instead, a comment about the memory updating **using** both time passed and victory counter may be more accurate (please refer to that update/PR for the exact comment)

2023-07-03 19:26 UTC, shoc71 commented on dont stop now/patch notes/updates.txt
>  - time passed function added
I looked through all the dsn_editor and dsn_levels PR's and comments and wasn't able to find any relevant comments. I had to find the version of the code that had the first implementation of the time function ([dsn_editor v.0.0.3](https://github.com/slysnivy/dont-stop-now-private/pull/6/files)) and used that code for commenting. I might have missed a few things but I think the current version of this patch notes has this fixed.

2023-07-03 19:29 UTC, shoc71 commented on dont stop now/patch notes/updates.txt
> +- tons of formatting changes being made (difference in which IDE python is being used; VSC and PyCharm)
I think it's worth mentioning as at times, it might have lead to some inconsistencies in the code but I'll remove it regardless as it's not relevant for mention here.

2023-07-03 19:30 UTC, shoc71 commented on dont stop now/patch notes/updates.txt
>  - victory counter added
I believe it was dsn_main v.0.1.6 that the comments about memory but that's all I could find about it.

2023-07-04 23:40 UTC, slysnivy approved these changes
I will change the time passed comment in the next PR

2023-07-04 23:40 UTC, merged